aug:
  image_aug: true
  masked_language_model: true
backbone: vgg11_bn
cnn:
  hidden: 256
  ks:
  - - 2
    - 2
  - - 2
    - 2
  - - 2
    - 1
  - - 2
    - 1
  - - 1
    - 1
  ss:
  - - 2
    - 2
  - - 2
    - 2
  - - 2
    - 1
  - - 2
    - 1
  - - 1
    - 1
dataloader:
  num_workers: 3
  pin_memory: true
dataset:
  data_root:
  - /media/hwr/TK/OCR/training_data
  - /media/hwr/TK/data_syn_ghep
  data_root_test:
  - /media/hwr/TK/OCR/training_data
  image_height: 32
  image_max_width: 1024
  image_min_width: 32
  name: hw
  train_annotation: labels.txt
  valid_annotation: labels.txt
device: cuda:0
optimizer:
  max_lr: 0.001
  pct_start: 0.1
predictor:
  beamsearch: false
pretrain:
  cached: /tmp/tranformerorc.pth
  id_or_url: 1nTKlEog9YFK74kPyX0qLwCWi60_YHHk4
  md5: efcabaa6d3adfca8e52bda2fd7d2ee04
quiet: false
seq_modeling: seq2seq
trainer:
  batch_size: 16
  checkpoint: /media/hwr/TK/vietocr_basecode/vgg_seq2seq_fix.pth
  export: ./weights_kalapa/
  iters: 2000000
  log: ./train.log
  metrics: 1000
  print_every: 10
  valid_every: 500
transformer:
  decoder_embedded: 256
  decoder_hidden: 256
  dropout: 0.1
  encoder_hidden: 256
  img_channel: 256
vocab: 'aAàÀảẢãÃáÁạẠăĂằẰẳẲẵẴắẮặẶâÂầẦẩẨẫẪấẤậẬbBcCdDđĐeEèÈẻẺẽẼéÉẹẸêÊềỀểỂễỄếẾệỆfFgGhHiIìÌỉỈĩĨíÍịỊjJkKlLmMnNoOòÒỏỎõÕóÓọỌôÔồỒổỔỗỖốỐộỘơƠờỜởỞỡỠớỚợỢpPqQrRsStTuUùÙủỦũŨúÚụỤưƯừỪửỬữỮứỨựỰvVwWxXyYỳỲỷỶỹỸýÝỵỴzZ0123456789!"#$%&''()*+,-./:;<=>?@[\]^_`{|}~ '
# vocab_new: aAàÀảẢãÃáÁạẠăĂằẰẳẲẵẴắẮặẶâÂầẦẩẨẫẪấẤậẬbBcCdDđĐeEèÈẻẺẽẼéÉẹẸêÊềỀểỂễỄếẾệỆfFgGhHiIìÌỉỈĩĨíÍịỊjJkKlLmMnNoOòÒỏỎõÕóÓọỌôÔồỒổỔỗỖốỐộỘơƠờỜởỞỡỠớỚợỢpPqQrRsStTuUùÙủỦũŨúÚụỤưƯừỪửỬữỮứỨựỰvVwWxXyYỳỲỷỶỹỸýÝỵỴzZ0123456789!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
weights: /media/hwr/TK/vietocr_basecode/vgg_seq2seq_fix.pth
